before:
  hooks:
    - go mod download

builds:
  - id: "gmn-cli"
    main: ./cmd/gmn/main.go
    binary: gmn
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - windows
      - darwin

archives:
  - name_template: "gmn{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

source:
  enabled: true
  name_template: "gmn{{ .Version }}.src"

checksum:
  name_template: "gmn{{ .Version }}.checksums.txt"

milestones:
  - close: true

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
