name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .editorconfig
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.15
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          golangci-lint run

  test:
    name: Test
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.platform }}
    needs: [ lint ]
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Run tests
        run: go test -v -race -covermode=atomic "-coverprofile=coverprofile.out" ./...
      - name: Report coverage
        uses: codecov/codecov-action@v1
        with:
          flags: ${{ matrix.platform }}
          file: coverprofile.out
          fail_ci_if_error: true

  build:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ^1.15
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Get dependencies
        run: |
          export GO111MODULE=on
          go get -v -t -d ./...
      - name: Build
        run: |
          export GO111MODULE=on
          GOOS=darwin  GOARCH=amd64 go build -o bin/gmn-ci-darwin-amd64      cmd/gmn/main.go
          GOOS=linux   GOARCH=amd64 go build -o bin/gmn-ci-linux-amd64       cmd/gmn/main.go
          GOOS=windows GOARCH=amd64 go build -o bin/gmn-ci-windows-amd64.exe cmd/gmn/main.go
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/
